version: 2.1

#orbs:
# aws_ecr: circleci/aws-ecr@8.1.3
  #reusable yaml files

#commands:

jobs:
  build-storefront:
    docker:
      - image: cimg/node:18.11.0

    steps:
      - checkout
     #- aws-ecr/build-and-push-image
        #- checkout
        #- path: "path/to/image"
        #- tag: version number
        #tag is how you reference the docker image

      - run:
          name: "What branch am I?"
          command: |
            echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
            - deps-v1--{{ checksum "astrowind/package-lock.json" }}
            - deps-v1--

      - run:
          name: "Build Storefront Deps"
          command:
            cd astrowind &&
            npm i
            
      - save_cache:
          paths:
            - astrowind/node_modules
          key: deps-v1--{{ checksum "astrowind/package-lock.json" }}

      - run:
          name: "Run scp to ec2"
          command: |

                  "scp -i $PEM -r /home/paxton/astrojs/ $USER@$IP:/home/$USER/astrojs"

      - run:
          name: "ssh command"
          command: |
            "ssh -i $PEM 'NPM i && npm run start'"

workflows:
  build:
    jobs:
      - build-storefront:
          context:
            - staging
          filters:
            branches:
              only:
                - astrowind_testing
